### ISSUE TITLE
Black polygon colliding with black matter from the outside

### ISSUE THREAD

**Issue by Ploppz** [Ploppz/universe#2]
When black polygon comes from the outside of the map and collides with black parts of the world, the program crashes (due to normal of collision being 0,0, which probably means it was inside of the black matter at the last frame before the crash). b9bc7498b95e7524b30367853cbda3e9567c99b6 is nice for testing this.

**Comment by kstrafe** [comment]
Was it completely fixed by inverting the mapping code for black tiles inside the get_normal function?

**Comment by Ploppz** [comment]
Yes it seems to work. Except rare (0,0)-normals but I think that's another issue.
