### ISSUE TITLE
Replacing glium

### ISSUE THREAD

**Issue by kstrafe** [Ploppz/universe#7]
https://users.rust-lang.org/t/glium-post-mortem/7063/10

Glium is dead. How do we replace it?

`glium` 0.22.0 (we use 0.16) is pretty bad too, it uses callbacks for handling input events (wtf, just return the damn polled event). So how do we replace this? With what do we replace it?

**Comment by Ploppz** [comment]
I don't think glium is that bad, despite what tomaka says in the post mortem. Glium tries to cover bugs in graphics drivers and is generally safer than alternatives.
Anyway, I'm not opposed to change either. `gfx-rs` is the most prominent alternative. That or some Vulkan wrapper.

**Comment by kstrafe** [comment]
It appears that glium corrupts the heap when running in release
`cargo run --release -- -c a`

**Comment by kstrafe** [comment]
Glium is replaced.
